
Load Libraries

```{r}
install.packages("tidyverse")
library(tidyverse)
install.packages("ggplot2")
library(ggplot2)
install.packages("here")
library("here")
install.packages("skimr")
library("skimr")
install.packages("janitor")
library("janitor")
install.packages("dplyr")
library("dplyr")
install.packages("readxl")
library(readxl)
```

Loading Data

```{r}
years <- c("2021-22", "2022-23", "2023-24")
bidding_data <- list()

# For loop to read datasets for each year
for (year in years) {
  file_path <- paste0("bidding_data/", year, "_T1.xls")
  bidding_data[[year]] <- read_excel(file_path)
}

# Access the datasets
bidding_data[["2021-22"]] # Data for 2021-22
bidding_data[["2022-23"]] # Data for 2022-23
bidding_data[["2023-24"]] # Data for 2023-24
```

Analysis of 2021-2022 IS210 bidding price

```{r}
bidding_2021_2022 <- bidding_data[["2021-22"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "IS210",`Median Bid` != 0, `Min Bid`   != 0) %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-") %>% 
  group_by(`Bidding Window`,Instructor_Section) 


ggplot(bidding_2021_2022, aes(x = `Bidding Window`, y = `Median Bid`)) +
geom_bar(stat = "identity", fill = "skyblue", color = "black",position = position_dodge2(padding = 100)) + geom_text(aes(label = round(`Median Bid`, 2)), vjust = 0.5, hjust = -0.1 ,  size = 3.5, position = position_dodge2(width = 0.9, padding = 10),angle=90) +
  theme_minimal() + 
  labs(x = "Bidding Window", y = "Median Bid", title = "IS210 2021-2022 Median Bid by Bidding Window & Instructor & section") + 
  facet_wrap(~ Instructor_Section) +  # Use correct column name for faceting
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_continuous(limits = c(0, 100))

ggsave("2021-2022_bidding.png", width = 10, height = 6)
  
```

Analysis of 2022-2023 IS210 bidding price

```{r}
bidding_2022_2023 <- bidding_data[["2022-23"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "IS210",`Median Bid` != 0, `Min Bid`   != 0) %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-") %>% 
  group_by(`Bidding Window`,Instructor_Section) 


ggplot(bidding_2022_2023, aes(x = `Bidding Window`, y = `Median Bid`)) +
geom_bar(stat = "identity", fill = "skyblue", color = "black",position = position_dodge2(padding = 100)) + geom_text(aes(label = round(`Median Bid`, 2)), vjust = 0.5, hjust = -0.1 ,  size = 3.5, position = position_dodge2(width = 0.9, padding = 10),angle=90) +
  theme_minimal() + 
  labs(x = "Bidding Window", y = "Median Bid", title = "IS210 2022-2023 Median Bid by Bidding Window & Instructor & section") + 
  facet_wrap(~ Instructor_Section) +  # Use correct column name for faceting
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_continuous(limits = c(0, 100))

ggsave("bidding_analysis_bar_charts/2022-2023_bidding.png", width = 10, height = 6)
```

Analysis of 2023-2024 IS210 bidding price

```{r}
bidding_2023_2024 <- bidding_data[["2023-24"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "IS210",`Median Bid` != 0, `Min Bid`   != 0) %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-") %>% 
  group_by(`Bidding Window`,Instructor_Section) 


ggplot(bidding_2023_2024, aes(x = `Bidding Window`, y = `Median Bid`)) +
geom_bar(stat = "identity", fill = "skyblue", color = "black",position = position_dodge2(padding = 100)) + geom_text(aes(label = round(`Median Bid`, 2)), vjust = 0.5, hjust = -0.1 ,  size = 3.5, position = position_dodge2(width = 0.9, padding = 10),angle=90) +
  theme_minimal() + 
  labs(x = "Bidding Window", y = "Median Bid", title = "IS210 2023-2024 Median Bid by Bidding Window & Instructor & section") + 
  facet_wrap(~ Instructor_Section) +  # Use correct column name for faceting
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_continuous(limits = c(0, 80)) 

ggsave("bidding_analysis_bar_charts/2023-2024_bidding.pdf", width = 10, height = 6)
```

bidding analysis for IS210 2022-2023 in Window 1 ONLY

```{r}
bidding_2022_2023 <- bidding_data[["2022-23"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "IS210",`Median Bid` != 0, `Min Bid`!= 0,`Bidding Window` == "Round 1 Window 1") %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-")


avg_median_bid <- mean(bidding_2022_2023$`Median Bid`, na.rm = TRUE)
avg_min_bid <- mean(bidding_2022_2023$`Min Bid`, na.rm = TRUE)

ggplot(bidding_2022_2023) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Median Bid`, color = "Median Bid"), size = 3) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Min Bid`, color = "Min Bid"), size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Median Bid`, label = `Median Bid`), vjust = -0.8, color = "blue", size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Min Bid`, label = `Min Bid`), vjust = 1.8, color = "red", size = 3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "IS210 2022-2023 Window 1 Bidding Price", y = "Bid Price") +
  scale_y_continuous(limits = c(0, 35)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Median Bid", "Min Bid"), name = "Bid Type") +
   geom_hline(yintercept = avg_median_bid, linetype = "dashed", color = "blue", size = 1) +
  geom_hline(yintercept = avg_min_bid, linetype = "dashed", color = "red", size = 1) +
  geom_text(aes(x = -0.5, y = avg_median_bid, label = paste0("Avg. Median Bid: ", round(avg_median_bid, 2))), color = "blue", vjust = 1.5, hjust = -0.1, size = 3.5) +
  geom_text(aes(x = -0.5, y = avg_min_bid, label = paste0("Avg. Min Bid: ", round(avg_min_bid, 2))), color = "red", vjust = 1.5, hjust = -0.1, size = 3.5) 
ggsave("Window_1_Analysis/window1_2022-2023.png",, width = 10, height = 6)
```

bidding analysis for IS210 2023-2024 in Window 1 ONLY

```{r}
bidding_2023_2024 <- bidding_data[["2023-24"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "IS210",`Median Bid` != 0, `Min Bid`!= 0,`Bidding Window` == "Round 1 Window 1") %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-")


avg_median_bid <- mean(bidding_2023_2024$`Median Bid`, na.rm = TRUE)
avg_min_bid <- mean(bidding_2023_2024$`Min Bid`, na.rm = TRUE)

ggplot(bidding_2023_2024) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Median Bid`, color = "Median Bid"), size = 3) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Min Bid`, color = "Min Bid"), size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Median Bid`, label = `Median Bid`), vjust = -0.8, color = "blue", size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Min Bid`, label = `Min Bid`), vjust = 1.8, color = "red", size = 3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "2023-2024 Window 1 Bidding Price",subtitle=" IS210 Business Process Analysis & Solutioning" ,y = "Bid Price") +
  scale_y_continuous(limits = c(0, 35)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Median Bid", "Min Bid"), name = "Bid Type") +
   geom_hline(yintercept = avg_median_bid, linetype = "dashed", color = "blue", size = 1) +
  geom_hline(yintercept = avg_min_bid, linetype = "dashed", color = "red", size = 1) +
  geom_text(aes(x = -0.5, y = avg_median_bid, label = paste0("Avg. Median Bid: ", round(avg_median_bid, 2))), color = "blue", vjust = 1.5, hjust = -0.1, size = 3.5) +
  geom_text(aes(x = -0.5, y = avg_min_bid, label = paste0("Avg. Min Bid: ", round(avg_min_bid, 2))), color = "red", vjust = 1.5, hjust = -0.1, size = 3.5) 
ggsave("Window_1_Analysis/window1_2023-2024.png",, width = 10, height = 6)
```

bidding analysis for COR1703 2023-2024 in Window 1 ONLY

```{r}
bidding_2023_2024 <- bidding_data[["2023-24"]] %>% 
  select(`Bidding Window`,`Course Code`,`Median Bid`,`Min Bid`  ,`Instructor`,Section) %>% 
  filter(`Course Code` == "COR1703",`Median Bid` != 0, `Min Bid`!= 0,`Bidding Window` == "Round 1 Window 1") %>% 
  unite("Instructor_Section",Instructor,Section,sep = "-")


avg_median_bid <- mean(bidding_2023_2024$`Median Bid`, na.rm = TRUE)
avg_min_bid <- mean(bidding_2023_2024$`Min Bid`, na.rm = TRUE)

ggplot(bidding_2023_2024) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Median Bid`, color = "Median Bid"), size = 3) +
  geom_point(mapping = aes(x = Instructor_Section, y = `Min Bid`, color = "Min Bid"), size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Median Bid`, label = `Median Bid`), vjust = -0.8, color = "blue", size = 3) +
  geom_text(mapping = aes(x = Instructor_Section, y = `Min Bid`, label = `Min Bid`), vjust = 1.8, color = "red", size = 3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "2023-2024 Window 1 Bidding Price",subtitle=" COR1703 Managing in a Volatile, Uncertain, Complex and Ambiguous Context" ,y = "Bid Price") +
  scale_y_continuous(limits = c(0, 25)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Median Bid", "Min Bid"), name = "Bid Type") +
   geom_hline(yintercept = avg_median_bid, linetype = "dashed", color = "blue", size = 1) +
  geom_hline(yintercept = avg_min_bid, linetype = "dashed", color = "red", size = 1) +
  geom_text(aes(x = -2, y = avg_median_bid, label = paste0("Avg. Median Bid: ", round(avg_median_bid, 2))), color = "blue", vjust = -1.5, hjust = -0.1, size = 3.5,fontface="bold") +
  geom_text(aes(x = -2, y = avg_min_bid, label = paste0("Avg. Min Bid: ", round(avg_min_bid, 2))), color = "red", vjust = -1.5, hjust = -0.1, size = 3.5,fontface="bold") 
ggsave("Window_1_Analysis/COR1703_window1_2023-2024.png",, width = 10, height = 6)
```
